name: Release

on:
  push:
    tags:
      - 'v*'
      - '!*nightly*'

jobs:
  release-nightly:
    uses: ./.github/workflows/release-nightly.yaml
    secrets: inherit

  release:
    runs-on: ubuntu-latest

    # Release the next `nightly` before a stable version
    # to prvent folks on pre-releases from being downgraded
    needs: release-nightly

    permissions:
      contents: write

    env:
      ATLASCODE_FX3_API_KEY: ${{ secrets.ATLASCODE_FX3_API_KEY }}
      ATLASCODE_FX3_ENVIRONMENT: ${{ vars.ATLASCODE_FX3_ENVIRONMENT }}
      ATLASCODE_FX3_TARGET_APP: ${{ vars.ATLASCODE_FX3_TARGET_APP }}
      ATLASCODE_FX3_TIMEOUT: ${{ vars.ATLASCODE_FX3_TIMEOUT }}

    steps:

      - uses: actions/checkout@v4

      - name: Evaluate version
        run: |
          PACKAGE_VERSION=${GITHUB_REF##*/v}
          ./scripts/version/assert-stable.sh $PACKAGE_VERSION
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "RELEASE_TAG=v${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "Using version '${PACKAGE_VERSION}'"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Set version in package.json
        run: npm version $PACKAGE_VERSION --no-git-tag-version --allow-same-version -f

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build and package the extension
        run: npm run extension:package

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:nocoverage

      - name: Generate SSL certs for E2E test
        run: npm run test:e2e:sslcerts

      - name: Fetch E2E image
        run: |
          docker pull ghcr.io/atlassian/atlascode-e2e:latest
          docker tag ghcr.io/atlassian/atlascode-e2e:latest atlascode-e2e

      - name: Run E2E tests
        run: npm run test:e2e:docker

      - name: Publish the extension
        run: |
          npx vsce publish \
            -p ${{ secrets.VSCE_MARKETPLACE_TOKEN }} \
            --baseContentUrl https://raw.githubusercontent.com/atlassian/atlascode/main/ \
            --packagePath atlascode-${PACKAGE_VERSION}.vsix

      # This step is optional, so setting 'continue-on-error' to true
      - name: Publish to OpenVSX
        continue-on-error: true
        run: |
          npx ovsx publish \
             -p ${{ secrets.OPENVSX_KEY }} \
            "atlascode-${PACKAGE_VERSION}.vsix"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: Release ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: |
            atlascode-${{ env.PACKAGE_VERSION }}.vsix
          fail_on_unmatched_files: true
